#! /bin/sh

# Copyright (C) 2005-2012 Free Software Foundation, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test -z "$VERBOSE" && {
   exec > /dev/null 2>&1
   set -x
}

cat >input <<EOF
a := 1
b := 2
c := 3
d := a + b * c
d
EOF

./calc++ input
./calc++ -p input

cat >input <<EOF
a := 1
d := a + b * c
EOF
./calc++ input

cat >input <<EOF
toto := 1
toto
EOF
./calc++ -s input

rm input
