#define yy_create_buffer gram__create_buffer
#define yy_delete_buffer gram__delete_buffer
#define yy_scan_buffer gram__scan_buffer
#define yy_scan_string gram__scan_string
#define yy_scan_bytes gram__scan_bytes
#define yy_flex_debug gram__flex_debug
#define yy_init_buffer gram__init_buffer
#define yy_flush_buffer gram__flush_buffer
#define yy_load_buffer_state gram__load_buffer_state
#define yy_switch_to_buffer gram__switch_to_buffer
#define yyin gram_in
#define yyleng gram_leng
#define yylex gram_lex
#define yyout gram_out
#define yyrestart gram_restart
#define yytext gram_text

#line 19 "lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
static yyconst short int yy_accept[361] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   99,   46,
       35,   34,   34,   39,   46,   38,   36,   46,   37,   31,
       33,   46,   30,   43,   32,   50,   51,   51,   52,   47,
       48,   77,   80,   80,   76,   47,   79,   48,   72,   75,
       75,   71,   74,   54,   55,   55,   53,   70,   57,   58,
       58,   56,   90,   91,   91,   82,   92,   81,   85,   92,
       47,   48,   87,   86,   94,   96,   96,   82,   95,   81,
       85,   97,   97,   97,   82,   81,   85,   35,   34,   34,
       34,   34,   45,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   42,   36,   40,
       41,   37,    0,   50,   51,   51,   51,   51,   49,   77,
       80,   80,   80,   80,   78,   72,   75,   75,   75,   75,
       73,   54,   55,   55,   55,   55,   69,   68,   69,   61,
       62,   63,   64,   65,   66,   67,   69,   58,   58,   58,
       58,   90,   91,   91,   91,   91,   88,    0,   88,    0,
       83,   84,   89,    0,   89,   94,   96,   96,   96,   96,
       93,   97,   97,   97,   97,   97,   83,   84,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       41,   44,    0,    0,    0,   84,   84,   84,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   59,   60,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   10,    0,    0,    0,
        0,    0,    0,   17,    0,    0,    0,    0,    0,   23,
        0,   26,    0,    0,   29,    0,    2,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   15,    0,    0,
        0,   20,    0,   22,   24,   27,    0,    1,    3,    0,
        0,    7,    0,    0,    0,    0,    0,    0,   16,    0,

        0,    0,    0,    0,    4,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,   28,    0,    0,
        0,    0,    0,    0,   13,   14,    0,   21,    0,    0,
        0,    0,    0,   11,    0,    0,    0,    5,    0,    0,
        0,    0,    0,    0,    0,    8,    0,   12,   19,   25,
        0,    0,    6,    0,    0,    0,    0,    0,    9,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    6,    7,    1,    8,    1,
        1,    9,    1,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   14,   14,   15,   16,   17,
       18,   19,    1,   20,   21,   21,   21,   21,   21,   21,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       22,   23,   24,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   11,   35,   36,   37,   38,
       39,   40,   11,   41,   42,   43,   44,   45,   11,   46,
       47,   11,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    2,    3,    4,    5,    6,    7,    8,    1,
        9,   10,   11,   11,    1,    1,    1,    1,   12,    5,
       11,   13,   14,   13,    9,   11,   11,   11,   11,   11,
       11,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    5,    1,    5
    } ;

static yyconst short int yy_base[387] =
    {   0,
        0,    0,   48,   51,   58,   61,   83,   86,   73,   94,
      108,  110,  131,  179,  227,  249,  116,  142,  819,  820,
      816,   55,   64,  820,  267,  820,    0,   44,   79,  820,
      820,    0,  820,  820,  820,    0,   97,   99,  805,  820,
      820,    0,  119,  122,  820,  820,    0,  820,    0,  126,
      138,  820,    0,    0,  145,  153,  820,  311,  820,  155,
      157,  820,    0,  159,  164,  820,  159,  820,   62,  164,
      820,  820,  820,  820,    0,  185,  189,  820,  766,  820,
      185,  192,  201,  203,  205,  207,  209,  813,  211,  213,
      216,  219,  820,  780,  783,   86,  778,   49,  198,  767,

      184,  776,  109,  203,  771,  778,  781,  820,    0,  820,
        0,  230,  787,    0,  242,  244,  255,  259,  820,    0,
      261,  263,  265,  272,  820,    0,  274,  276,  278,  280,
      820,    0,  282,  284,  286,  288,  820,  820,  792,  820,
      820,  820,  820,  820,  820,  820,    0,  296,  298,  314,
      316,    0,  318,  322,  324,  326,  820,  318,  322,    0,
      820,    0,  820,  326,  330,    0,  342,  344,  347,  355,
      820,  357,  359,  361,  363,  365,  367,  369,  766,  144,
      762,  762,  144,  770,  772,  762,  364,  768,  754,  168,
      755,  763,  764,  767,  751,  756,  750,  755,  747,  759,

        0,  820,  773,    0,  766,    0,  372,  375,  758,  739,
      748,  738,  741,  749,  748,  747,  733,  749,  744,  737,
      746,  730,  730,  741,  730,  737,  733,  729,  723,  726,
      732,  731,  721,  732,  730,  820,  820,  371,  716,  724,
      717,  713,  712,  724,  741,  721,  820,  706,  230,  714,
      705,  709,  701,  820,  701,  370,  700,  712,  698,  820,
      702,  820,  701,  699,  820,  690,  820,  706,  691,  373,
      691,  693,  376,  698,  691,  692,  687,  820,  685,  697,
      686,  820,  682,  820,  378,  820,  682,  820,  681,  668,
      647,  820,  627,  626,  612,  607,  615,  605,  820,  601,

      615,  601,  594,  604,  820,  588,  599,  598,  583,  588,
      571,  558,  571,  820,  537,  536,  547,  820,  510,  507,
      516,  501,  497,  503,  820,  820,  491,  820,  502,  363,
      373,  358,  347,  820,  348,  325,  317,  820,  302,  287,
      279,  267,  263,  265,  251,  820,  229,  820,  820,  820,
      240,  380,  820,  229,  192,  164,   85,   62,  820,  820,
      405,  419,  433,  447,  461,  475,  489,  503,  227,  517,
      531,  545,  557,  571,  583,  597,  610,  624,  638,  652,
      666,   84,  680,  694,  708,   58
    } ;

static yyconst short int yy_def[387] =
    {   0,
      360,    1,  361,  361,  362,  362,  363,  363,  364,  364,
      365,  365,  366,  366,  367,  367,  368,  368,  360,  360,
      360,  360,  360,  360,  360,  360,  369,  360,  360,  360,
      360,  370,  360,  360,  360,  371,  360,  360,  360,  360,
      360,  372,  360,  360,  360,  360,  373,  360,  374,  360,
      360,  360,  375,  376,  360,  360,  360,  377,  360,  360,
      360,  360,  378,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  379,  360,  360,  360,  360,  360,
      360,  380,  380,  380,  380,  380,  380,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  369,  360,
      381,  360,  370,  371,  360,  360,  360,  360,  360,  372,
      360,  360,  360,  360,  360,  374,  360,  360,  360,  360,
      360,  376,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  382,  360,  360,  360,
      360,  378,  360,  360,  360,  360,  360,  360,  360,  383,
      360,  384,  360,  360,  360,  379,  360,  360,  360,  360,
      360,  380,  380,  380,  380,  380,  380,  385,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      381,  360,  360,  386,  383,  384,  385,  385,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,    0,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360
    } ;

static yyconst short int yy_nxt[871] =
    {   0,
       20,   21,   22,   23,   24,   20,   25,   26,   20,   20,
       27,   28,   29,   29,   30,   31,   32,   33,   20,   20,
       27,   20,   20,   20,   20,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   34,   35,   20,
       37,   38,  110,   37,   38,  111,   39,   89,   90,   39,
       43,   44,   45,   43,   44,   45,   91,   92,  237,   40,
      161,   41,   40,  162,   41,   55,   56,   57,  184,   46,
       47,   48,   46,   47,   48,   50,   51,  185,   50,   51,
       52,  112,  112,   52,  204,   58,   55,   56,   57,  115,

      116,  117,  118,  359,   46,   53,   48,   46,   53,   48,
       60,   61,   60,   61,  358,   62,   58,   62,   83,   84,
       85,  121,  122,   86,  123,  124,  181,   87,  127,  128,
       58,  182,   58,   64,   65,   66,   67,   46,   68,   48,
      129,  130,   69,  193,   83,   84,   85,  133,  134,   86,
       70,  194,   71,   87,   72,  135,  136,  148,  149,  150,
      151,  153,  154,   46,  157,   48,  155,  156,  158,  163,
      210,  159,  159,  164,  211,  160,  165,  165,   73,  215,
       74,   64,   65,   66,   67,  212,   68,  167,  168,  216,
       69,  169,  170,  161,  173,  174,  162,  224,   70,  357,

       71,  225,   72,  173,  175,  176,  174,  173,  174,  173,
      174,  173,  174,   89,   90,   91,   92,  177,   89,   90,
      178,   91,   92,  186,  190,  356,   73,  191,   74,   76,
       77,   78,  195,   79,   80,  109,  187,  109,   81,  275,
      188,  196,  112,  112,  115,  116,  117,  118,   46,  197,
       48,   76,   77,   78,  275,   79,   80,  115,  116,  355,
       81,  117,  118,  121,  122,  123,  124,  121,  122,  353,
       46,  352,   48,   93,  123,  124,  127,  128,  129,  130,
      127,  128,  129,  130,  133,  134,  135,  136,  133,  134,
      135,  136,  351,   94,  350,   95,   96,   97,  148,  149,

      150,  151,   98,  349,   99,  100,  101,  102,  103,  104,
      105,  106,  348,  107,  108,  138,  148,  149,  150,  151,
      153,  154,  347,  139,  155,  156,  153,  154,  155,  156,
      159,  159,  346,  138,  159,  159,  140,  141,  165,  165,
      345,  142,  165,  165,  167,  168,  169,  170,  143,  167,
      168,  144,  344,  145,  343,  146,  147,  169,  170,  173,
      174,  173,  175,  176,  174,  176,  174,  173,  175,  173,
      174,  173,  208,  220,  173,  208,  157,  176,  208,  281,
      158,  342,  291,  159,  159,  294,  341,  303,  220,  354,
      206,  340,  206,  206,  281,  206,  206,  291,  206,  339,

      294,  221,  303,  338,  354,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   75,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  337,  113,
      113,  114,  336,  335,  114,  114,  114,  114,  334,  114,
      114,  114,  114,  333,  114,  120,  332,  331,  330,  120,
      120,  120,  120,  120,  120,  120,  120,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  126,  329,  328,  126,  126,  126,  327,  126,  126,
      126,  126,  126,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  132,  326,  325,

      324,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  152,  323,  322,  321,  320,  152,
      319,  152,  152,  318,  152,  152,  317,  152,  166,  316,
      315,  314,  166,  313,  312,  166,  166,  311,  166,  166,
      310,  166,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  309,  172,  201,  308,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  307,  205,  205,  206,  306,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  206,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  305,  304,  302,  301,  300,  299,  298,  297,
      296,  295,  293,  292,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  280,  279,  278,  277,  276,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  223,  222,  219,  218,

      217,  214,  213,  209,  203,  202,  200,  199,  198,  192,
      189,  183,  180,  179,   88,  171,  119,   88,  360,   19,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360
    } ;

static yyconst short int yy_chk[871] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,   28,    4,    4,   28,    3,   22,   22,    4,
        5,    5,    5,    6,    6,    6,   23,   23,  386,    3,
       69,    3,    4,   69,    4,    9,    9,    9,   98,    5,
        5,    5,    6,    6,    6,    7,    7,   98,    8,    8,
        7,   29,   29,    8,  382,    9,   10,   10,   10,   37,

       37,   38,   38,  358,    7,    7,    7,    8,    8,    8,
       11,   11,   12,   12,  357,   11,   10,   12,   17,   17,
       17,   43,   43,   17,   44,   44,   96,   17,   50,   50,
       11,   96,   12,   13,   13,   13,   13,   17,   13,   17,
       51,   51,   13,  103,   18,   18,   18,   55,   55,   18,
       13,  103,   13,   18,   13,   56,   56,   60,   60,   61,
       61,   64,   64,   18,   67,   18,   65,   65,   67,   70,
      180,   67,   67,   70,  180,   67,   70,   70,   13,  183,
       13,   14,   14,   14,   14,  180,   14,   76,   76,  183,
       14,   77,   77,   81,   82,   82,   81,  190,   14,  356,

       14,  190,   14,   83,   83,   84,   84,   85,   85,   86,
       86,   87,   87,   89,   89,   90,   90,   87,   91,   91,
       87,   92,   92,   99,  101,  355,   14,  101,   14,   15,
       15,   15,  104,   15,   15,  369,   99,  369,   15,  249,
       99,  104,  112,  112,  115,  115,  116,  116,   15,  104,
       15,   16,   16,   16,  249,   16,   16,  117,  117,  354,
       16,  118,  118,  121,  121,  122,  122,  123,  123,  351,
       16,  347,   16,   25,  124,  124,  127,  127,  128,  128,
      129,  129,  130,  130,  133,  133,  134,  134,  135,  135,
      136,  136,  345,   25,  344,   25,   25,   25,  148,  148,

      149,  149,   25,  343,   25,   25,   25,   25,   25,   25,
       25,   25,  342,   25,   25,   58,  150,  150,  151,  151,
      153,  153,  341,   58,  154,  154,  155,  155,  156,  156,
      158,  158,  340,   58,  159,  159,   58,   58,  164,  164,
      339,   58,  165,  165,  167,  167,  168,  168,   58,  169,
      169,   58,  337,   58,  336,   58,   58,  170,  170,  172,
      172,  173,  173,  174,  174,  175,  175,  176,  176,  177,
      177,  178,  178,  187,  207,  207,  238,  208,  208,  256,
      238,  335,  270,  238,  238,  273,  333,  285,  187,  352,
      178,  332,  178,  207,  256,  207,  208,  270,  208,  331,

      273,  187,  285,  330,  352,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,

      367,  367,  367,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  329,  370,
      370,  371,  327,  324,  371,  371,  371,  371,  323,  371,
      371,  371,  371,  322,  371,  372,  321,  320,  319,  372,
      372,  372,  372,  372,  372,  372,  372,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  374,  317,  316,  374,  374,  374,  315,  374,  374,
      374,  374,  374,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  376,  313,  312,

      311,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  378,  310,  309,  308,  307,  378,
      306,  378,  378,  304,  378,  378,  303,  378,  379,  302,
      301,  300,  379,  298,  297,  379,  379,  296,  379,  379,
      295,  379,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  294,  380,  381,  293,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  291,  383,  383,  384,  290,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  289,  287,  283,  281,  280,  279,  277,  276,
      275,  274,  272,  271,  269,  268,  266,  264,  263,  261,
      259,  258,  257,  255,  253,  252,  251,  250,  248,  246,
      245,  244,  243,  242,  241,  240,  239,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  205,  203,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  189,  188,  186,  185,

      184,  182,  181,  179,  139,  113,  107,  106,  105,  102,
      100,   97,   95,   94,   88,   79,   39,   21,   19,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[98] =
    {   0,
      122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
      132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
      142,  143,  144,  145,  146,  147,  148,  149,  150,  152,
      153,  154,  155,  157,  158,  159,  164,  167,  170,  173,
      174,  177,  180,  183,  191,  197,  213,  214,  225,  237,
      238,  239,  256,  265,  267,  287,  301,  303,  323,  335,
      339,  340,  341,  342,  343,  344,  345,  346,  347,  353,
      364,  370,  371,  373,  375,  393,  399,  400,  402,  404,
      422,  425,  428,  429,  432,  443,  454,  456,  458,  461,
      462,  465,  485,  492,  493,  494,  514

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan-gram.l"
#define INITIAL 0
/* Bison Grammar Scanner                             -*- C -*-
   Copyright (C) 2002 Free Software Foundation, Inc.

   This file is part of Bison, the GNU Compiler Compiler.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
   02111-1307  USA
*/
#define YY_NO_UNPUT 1
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#line 26 "scan-gram.l"
#include "system.h"
#include "complain.h"
#include "quote.h"
#include "getargs.h"
#include "gram.h"
#include "reader.h"

/* Each time we match a string, move the end cursor to its end. */
#define YY_USER_INIT				\
do {						\
  LOCATION_RESET (*yylloc);			\
   /* This is only to avoid GCC warnings. */	\
  if (yycontrol) {;};				\
} while (0)

#define YY_USER_ACTION  LOCATION_COLUMNS (*yylloc, yyleng)
#define YY_LINES        LOCATION_LINES (*yylloc, yyleng); lineno += yyleng;
#define YY_STEP         LOCATION_STEP (*yylloc)


/* STRING_OBSTACK -- Used to store all the characters that we need to
   keep (to construct ID, STRINGS etc.).  Use the following macros to
   use it.

   Use YY_OBS_GROW to append what has just been matched, and
   YY_OBS_FINISH to end the string (it puts the ending 0).
   YY_OBS_FINISH also stores this string in LAST_STRING, which can be
   used, and which is used by YY_OBS_FREE to free the last string.  */

static struct obstack string_obstack;
char *last_string;

#define YY_OBS_GROW   \
  obstack_grow (&string_obstack, yytext, yyleng)

#define YY_OBS_FINISH					\
  do {							\
    obstack_1grow (&string_obstack, '\0');		\
    last_string = obstack_finish (&string_obstack);	\
  } while (0)

#define YY_OBS_FREE						\
  do {								\
    obstack_free (&string_obstack, last_string);		\
  } while (0)

void
scanner_last_string_free (void)
{
  YY_OBS_FREE;
}


static int braces_level = 0;
static int percent_percent_count = 0;

static void handle_dollar PARAMS ((braced_code_t code_kind,
				   char *cp, location_t location));
static void handle_at PARAMS ((braced_code_t code_kind,
			       char *cp, location_t location));

#define SC_COMMENT 1

#define SC_STRING 2
#define SC_CHARACTER 3

#define SC_ESCAPED_STRING 4
#define SC_ESCAPED_CHARACTER 5

#define SC_BRACED_CODE 6
#define SC_PROLOGUE 7
#define SC_EPILOGUE 8

#line 817 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 98 "scan-gram.l"


  /* At each yylex invocation, mark the current position as the
     start of the next token.  */
#define TR_POS 0
#if TR_POS
  fprintf (stderr, "FOO1: %p: ", yylloc);
  LOCATION_PRINT (stderr, *yylloc);
  fprintf (stderr, "\n");
#endif
  YY_STEP;
#if TR_POS
  fprintf (stderr, "BAR1: ");
  LOCATION_PRINT (stderr, *yylloc);
  fprintf (stderr, "\n");
#endif



  /*----------------------------.
  | Scanning Bison directives.  |
  `----------------------------*/
#line 1002 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 361 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 820 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 98 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 98 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 99 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;



case 1:
YY_RULE_SETUP
#line 122 "scan-gram.l"
return PERCENT_NONASSOC;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 123 "scan-gram.l"
return PERCENT_DEBUG;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 124 "scan-gram.l"
return PERCENT_DEFINE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 125 "scan-gram.l"
return PERCENT_DEFINES;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 126 "scan-gram.l"
return PERCENT_DESTRUCTOR;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 127 "scan-gram.l"
return PERCENT_ERROR_VERBOSE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 128 "scan-gram.l"
return PERCENT_EXPECT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 129 "scan-gram.l"
return PERCENT_FILE_PREFIX;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 130 "scan-gram.l"
return PERCENT_YACC;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "scan-gram.l"
return PERCENT_LEFT;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 132 "scan-gram.l"
return PERCENT_LOCATIONS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 133 "scan-gram.l"
return PERCENT_NAME_PREFIX;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 134 "scan-gram.l"
return PERCENT_NO_LINES;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 135 "scan-gram.l"
return PERCENT_NONASSOC;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 136 "scan-gram.l"
return PERCENT_NTERM;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 137 "scan-gram.l"
return PERCENT_OUTPUT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 138 "scan-gram.l"
return PERCENT_PREC;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 139 "scan-gram.l"
return PERCENT_PRINTER;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 140 "scan-gram.l"
return PERCENT_PURE_PARSER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 141 "scan-gram.l"
return PERCENT_RIGHT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 142 "scan-gram.l"
return PERCENT_SKELETON;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 143 "scan-gram.l"
return PERCENT_START;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 144 "scan-gram.l"
return PERCENT_TOKEN;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 145 "scan-gram.l"
return PERCENT_TOKEN;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 146 "scan-gram.l"
return PERCENT_TOKEN_TABLE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 147 "scan-gram.l"
return PERCENT_TYPE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 148 "scan-gram.l"
return PERCENT_UNION;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 149 "scan-gram.l"
return PERCENT_VERBOSE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 150 "scan-gram.l"
return PERCENT_YACC;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 152 "scan-gram.l"
return EQUAL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 153 "scan-gram.l"
return COLON;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 154 "scan-gram.l"
return PIPE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 155 "scan-gram.l"
return SEMICOLON;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 157 "scan-gram.l"
YY_LINES; YY_STEP;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 158 "scan-gram.l"
YY_STEP;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 159 "scan-gram.l"
{
    yylval->symbol = getsym (yytext, *yylloc);
    return ID;
  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 164 "scan-gram.l"
yylval->integer = strtol (yytext, 0, 10); return INT;
	YY_BREAK
/* Characters.  We don't check there is only one.  */
case 38:
YY_RULE_SETUP
#line 167 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_ESCAPED_CHARACTER);
	YY_BREAK
/* Strings. */
case 39:
YY_RULE_SETUP
#line 170 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_ESCAPED_STRING);
	YY_BREAK
/* Comments. */
case 40:
YY_RULE_SETUP
#line 173 "scan-gram.l"
yy_push_state (SC_COMMENT);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 174 "scan-gram.l"
YY_STEP;
	YY_BREAK
/* Prologue. */
case 42:
YY_RULE_SETUP
#line 177 "scan-gram.l"
yy_push_state (SC_PROLOGUE);
	YY_BREAK
/* Code in between braces.  */
case 43:
YY_RULE_SETUP
#line 180 "scan-gram.l"
YY_OBS_GROW; ++braces_level; yy_push_state (SC_BRACED_CODE);
	YY_BREAK
/* A type. */
case 44:
YY_RULE_SETUP
#line 183 "scan-gram.l"
{
    obstack_grow (&string_obstack, yytext + 1, yyleng - 2);
    YY_OBS_FINISH;
    yylval->string = last_string;
    return TYPE;
  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 191 "scan-gram.l"
{
    if (++percent_percent_count == 2)
      yy_push_state (SC_EPILOGUE);
    return PERCENT_PERCENT;
  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 197 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": invalid character: `%c'\n", *yytext);
    YY_STEP;
  }
	YY_BREAK

/*------------------------------------------------------------.
  | Whatever the start condition (but those which correspond to |
  | entity `swallowed' by Bison: SC_ESCAPED_STRING and          |
  | SC_ESCAPED_CHARACTER), no M4 character must escape as is.   |
  `------------------------------------------------------------*/


case 47:
YY_RULE_SETUP
#line 213 "scan-gram.l"
if (YY_START != SC_COMMENT) obstack_sgrow (&string_obstack, "@<:@");
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 214 "scan-gram.l"
if (YY_START != SC_COMMENT) obstack_sgrow (&string_obstack, "@:>@");
	YY_BREAK

/*-----------------------------------------------------------.
  | Scanning a C comment. The initial `/ *' is already eaten.  |
  `-----------------------------------------------------------*/


case 49:
YY_RULE_SETUP
#line 225 "scan-gram.l"
{ /* End of the comment. */
    if (yy_top_state () == INITIAL)
      {
	YY_STEP;
      }
    else
      {
	YY_OBS_GROW;
      }
    yy_pop_state ();
  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 237 "scan-gram.l"
if (yy_top_state () != INITIAL) YY_OBS_GROW;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 238 "scan-gram.l"
if (yy_top_state () != INITIAL) YY_OBS_GROW; YY_LINES;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 239 "scan-gram.l"
/* Stray `*'. */if (yy_top_state () != INITIAL) YY_OBS_GROW;
	YY_BREAK
case YY_STATE_EOF(SC_COMMENT):
#line 241 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a comment\n");
    yy_pop_state ();
  }
	YY_BREAK

/*----------------------------------------------------------------.
  | Scanning a C string, including its escapes.  The initial `"' is |
  | already eaten.                                                  |
  `----------------------------------------------------------------*/


case 53:
YY_RULE_SETUP
#line 256 "scan-gram.l"
{
    assert (yy_top_state () == INITIAL);
    YY_OBS_GROW;
    YY_OBS_FINISH;
    yylval->string = last_string;
    yy_pop_state ();
    return STRING;
  }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 265 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 267 "scan-gram.l"
obstack_1grow (&string_obstack, '\n'); YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_ESCAPED_STRING):
#line 269 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a string\n");
    assert (yy_top_state () == INITIAL);
    YY_OBS_FINISH;
    yylval->string = last_string;
    yy_pop_state ();
    return STRING;
  }
	YY_BREAK

/*---------------------------------------------------------------.
  | Scanning a C character, decoding its escapes.  The initial "'" |
  | is already eaten.                                              |
  `---------------------------------------------------------------*/


case 56:
YY_RULE_SETUP
#line 287 "scan-gram.l"
{
    YY_OBS_GROW;
    assert (yy_top_state () == INITIAL);
    {
      YY_OBS_FINISH;
      yylval->symbol = getsym (last_string, *yylloc);
      symbol_class_set (yylval->symbol, token_sym);
      symbol_user_token_number_set (yylval->symbol, last_string[1]);
      YY_OBS_FREE;
      yy_pop_state ();
      return ID;
    }
  }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 301 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 303 "scan-gram.l"
obstack_1grow (&string_obstack, '\n'); YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_ESCAPED_CHARACTER):
#line 305 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a character\n");
    assert (yy_top_state () == INITIAL);
    YY_OBS_FINISH;
    yylval->string = last_string;
    yy_pop_state ();
    return CHARACTER;
  }
	YY_BREAK

/*----------------------------.
  | Decode escaped characters.  |
  `----------------------------*/


case 59:
YY_RULE_SETUP
#line 323 "scan-gram.l"
{
    long c = strtol (yytext + 1, 0, 8);
    if (c > 255)
      {
	LOCATION_PRINT (stderr, *yylloc);
	fprintf (stderr, ": invalid escape: %s\n", quote (yytext));
	YY_STEP;
      }
    else
      obstack_1grow (&string_obstack, c);
  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 335 "scan-gram.l"
{
    obstack_1grow (&string_obstack, strtol (yytext + 2, 0, 16));
  }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 339 "scan-gram.l"
obstack_1grow (&string_obstack, '\a');
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 340 "scan-gram.l"
obstack_1grow (&string_obstack, '\b');
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 341 "scan-gram.l"
obstack_1grow (&string_obstack, '\f');
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 342 "scan-gram.l"
obstack_1grow (&string_obstack, '\n');
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 343 "scan-gram.l"
obstack_1grow (&string_obstack, '\r');
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 344 "scan-gram.l"
obstack_1grow (&string_obstack, '\t');
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 345 "scan-gram.l"
obstack_1grow (&string_obstack, '\v');
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 346 "scan-gram.l"
obstack_1grow (&string_obstack, yytext[1]);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 347 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unrecognized escape: %s\n", quote (yytext));
    YY_OBS_GROW;
  }
	YY_BREAK
/* FLex wants this rule, in case of a `\<<EOF>>'. */
case 70:
YY_RULE_SETUP
#line 353 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK

/*----------------------------------------------------------.
  | Scanning a C character without decoding its escapes.  The |
  | initial "'" is already eaten.                             |
  `----------------------------------------------------------*/


case 71:
YY_RULE_SETUP
#line 364 "scan-gram.l"
{
    YY_OBS_GROW;
    assert (yy_top_state () != INITIAL);
    yy_pop_state ();
  }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 370 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 371 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
/* FLex wants this rule, in case of a `\<<EOF>>'. */
case 74:
YY_RULE_SETUP
#line 373 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 375 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_CHARACTER):
#line 377 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a character\n");
    assert (yy_top_state () != INITIAL);
    yy_pop_state ();
  }
	YY_BREAK

/*----------------------------------------------------------------.
  | Scanning a C string, without decoding its escapes.  The initial |
  | `"' is already eaten.                                           |
  `----------------------------------------------------------------*/


case 76:
YY_RULE_SETUP
#line 393 "scan-gram.l"
{
    assert (yy_top_state () != INITIAL);
    YY_OBS_GROW;
    yy_pop_state ();
  }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 399 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 400 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
/* FLex wants this rule, in case of a `\<<EOF>>'. */
case 79:
YY_RULE_SETUP
#line 402 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 404 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_STRING):
#line 406 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a string\n");
    assert (yy_top_state () != INITIAL);
    yy_pop_state ();
  }
	YY_BREAK

/*---------------------------------------------------.
  | Strings, comments etc. can be found in user code.  |
  `---------------------------------------------------*/


/* Characters.  We don't check there is only one.  */
case 81:
YY_RULE_SETUP
#line 422 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_CHARACTER);
	YY_BREAK
/* Strings. */
case 82:
YY_RULE_SETUP
#line 425 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_STRING);
	YY_BREAK
/* Comments. */
case 83:
YY_RULE_SETUP
#line 428 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_COMMENT);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 429 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
/* Not comments. */
case 85:
YY_RULE_SETUP
#line 432 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK

/*---------------------------------------------------------------.
  | Scanning some code in braces (%union and actions). The initial |
  | "{" is already eaten.                                          |
  `---------------------------------------------------------------*/


case 86:
YY_RULE_SETUP
#line 443 "scan-gram.l"
{
    YY_OBS_GROW;
    if (--braces_level == 0)
      {
	yy_pop_state ();
	YY_OBS_FINISH;
	yylval->string = last_string;
	return BRACED_CODE;
      }
  }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 454 "scan-gram.l"
YY_OBS_GROW; braces_level++;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 456 "scan-gram.l"
{ handle_dollar (current_braced_code,
						   yytext, *yylloc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 458 "scan-gram.l"
{ handle_at (current_braced_code,
					       yytext, *yylloc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 461 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 462 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
/* A lose $, or /, or etc. */
case 92:
YY_RULE_SETUP
#line 465 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case YY_STATE_EOF(SC_BRACED_CODE):
#line 467 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a braced code\n");
    yy_pop_state ();
    YY_OBS_FINISH;
    yylval->string = last_string;
    return BRACED_CODE;
  }
	YY_BREAK

/*--------------------------------------------------------------.
  | Scanning some prologue: from "%{" (already scanned) to "%}".  |
  `--------------------------------------------------------------*/


case 93:
YY_RULE_SETUP
#line 485 "scan-gram.l"
{
    yy_pop_state ();
    YY_OBS_FINISH;
    yylval->string = last_string;
    return PROLOGUE;
  }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 492 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 493 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 494 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_PROLOGUE):
#line 496 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a prologue\n");
    yy_pop_state ();
    YY_OBS_FINISH;
    yylval->string = last_string;
    return PROLOGUE;
  }
	YY_BREAK

/*---------------------------------------------------------------.
  | Scanning the epilogue (everything after the second "%%", which |
  | has already been eaten.                                        |
  `---------------------------------------------------------------*/


case 97:
YY_RULE_SETUP
#line 514 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case YY_STATE_EOF(SC_EPILOGUE):
#line 516 "scan-gram.l"
{
    yy_pop_state ();
    YY_OBS_FINISH;
    yylval->string = last_string;
    return EPILOGUE;
  }
	YY_BREAK

case 98:
YY_RULE_SETUP
#line 525 "scan-gram.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1847 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 361 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 361 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 360);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 525 "scan-gram.l"


/*------------------------------------------------------------------.
| TEXT is pointing to a wannabee semantic value (i.e., a `$').      |
|                                                                   |
| Possible inputs: $[<TYPENAME>]($|integer)                         |
|                                                                   |
| Output to the STRING_OBSTACK a reference to this semantic value.  |
`------------------------------------------------------------------*/

static inline void
handle_action_dollar (char *text, location_t location)
{
  const char *type_name = NULL;
  char *cp = text + 1;

  /* Get the type name if explicit. */
  if (*cp == '<')
    {
      type_name = ++cp;
      while (*cp != '>')
	++cp;
      *cp = '\0';
      ++cp;
    }

  if (*cp == '$')
    {
      if (!type_name)
	type_name = symbol_list_n_type_name_get (current_rule, location, 0);
      if (!type_name && typed)
	complain_at (location, _("$$ of `%s' has no declared type"),
		     symbol_tag_get (current_rule->sym));
      if (!type_name)
	type_name = "";
      obstack_fgrow1 (&string_obstack,
		      "]b4_lhs_value([%s])[", type_name);
    }
  else if (isdigit (*cp) || *cp == '-')
    {
      /* RULE_LENGTH is the number of values in the current rule so
	 far, which says where to find `$0' with respect to the top of
	 the stack.  It is not the same as the rule->length in the
	 case of mid rule actions.  */
      int rule_length = symbol_list_length (current_rule->next);
      int n = strtol (cp, &cp, 10);

      if (n > rule_length)
	complain_at (location, _("invalid value: %s%d"), "$", n);
      else
	{
	  if (!type_name && n > 0)
	    type_name = symbol_list_n_type_name_get (current_rule, location,
						     n);
	  if (!type_name && typed)
	    complain_at (location, _("$%d of `%s' has no declared type"),
		      n, symbol_tag_get (current_rule->sym));
	  if (!type_name)
	    type_name = "";
	  obstack_fgrow3 (&string_obstack,
			  "]b4_rhs_value([%d], [%d], [%s])[",
			  rule_length, n, type_name);
	}
    }
  else
    {
      complain_at (location, _("%s is invalid"), quote (text));
    }
}


/*---------------------------------------------------------------.
| TEXT is expexted tp be $$ in some code associated to a symbol: |
| destructor or printer.                                         |
`---------------------------------------------------------------*/

static inline void
handle_symbol_code_dollar (char *text, location_t location)
{
  char *cp = text + 1;
  if (*cp == '$')
    obstack_sgrow (&string_obstack, "]b4_dollar_dollar[");
  else
    complain_at (location, _("%s is invalid"), quote (text));
}


/*-----------------------------------------------------------------.
| Dispatch onto handle_action_dollar, or handle_destructor_dollar, |
| depending upon CODE_KIND.                                        |
`-----------------------------------------------------------------*/

static void
handle_dollar (braced_code_t braced_code_kind,
	       char *text, location_t location)
{
  switch (braced_code_kind)
    {
    case action_braced_code:
      handle_action_dollar (text, location);
      break;

    case destructor_braced_code:
    case printer_braced_code:
      handle_symbol_code_dollar (text, location);
      break;
    }
}


/*------------------------------------------------------.
| TEXT is a location token (i.e., a `@...').  Output to |
| STRING_OBSTACK a reference to this location.          |
`------------------------------------------------------*/

static inline void
handle_action_at (char *text, location_t location)
{
  char *cp = text + 1;
  locations_flag = 1;

  if (*cp == '$')
    {
      obstack_sgrow (&string_obstack, "]b4_lhs_location[");
    }
  else if (isdigit (*cp) || *cp == '-')
    {
      /* RULE_LENGTH is the number of values in the current rule so
	 far, which says where to find `$0' with respect to the top of
	 the stack.  It is not the same as the rule->length in the
	 case of mid rule actions.  */
      int rule_length = symbol_list_length (current_rule->next);
      int n = strtol (cp, &cp, 10);

      if (n > rule_length)
	complain_at (location, _("invalid value: %s%d"), "@", n);
      else
	obstack_fgrow2 (&string_obstack, "]b4_rhs_location([%d], [%d])[",
			rule_length, n);
    }
  else
    {
      complain_at (location, _("%s is invalid"), quote (text));
    }
}


/*---------------------------------------------------------------.
| TEXT is expexted tp be @$ in some code associated to a symbol: |
| destructor or printer.                                         |
`---------------------------------------------------------------*/

static inline void
handle_symbol_code_at (char *text, location_t location)
{
  char *cp = text + 1;
  if (*cp == '$')
    obstack_sgrow (&string_obstack, "]b4_at_dollar[");
  else
    complain_at (location, _("%s is invalid"), quote (text));
}


/*-------------------------------------------------------------------.
| Dispatch onto handle_action_at, or handle_destructor_at, depending |
| upon CODE_KIND.                                                    |
`-------------------------------------------------------------------*/

static void
handle_at (braced_code_t braced_code_kind,
	   char *text, location_t location)
{
  switch (braced_code_kind)
    {
    case action_braced_code:
      handle_action_at (text, location);
      break;

    case destructor_braced_code:
    case printer_braced_code:
      handle_symbol_code_at (text, location);
      break;
    }
}


/*-------------------------.
| Initialize the scanner.  |
`-------------------------*/

void
scanner_initialize (void)
{
  obstack_init (&string_obstack);
}


/*-----------------------------------------------.
| Free all the memory allocated to the scanner.  |
`-----------------------------------------------*/

void
scanner_free (void)
{
  obstack_free (&string_obstack, 0);
}
