#define yy_create_buffer gram__create_buffer
#define yy_delete_buffer gram__delete_buffer
#define yy_scan_buffer gram__scan_buffer
#define yy_scan_string gram__scan_string
#define yy_scan_bytes gram__scan_bytes
#define yy_flex_debug gram__flex_debug
#define yy_init_buffer gram__init_buffer
#define yy_flush_buffer gram__flush_buffer
#define yy_load_buffer_state gram__load_buffer_state
#define yy_switch_to_buffer gram__switch_to_buffer
#define yyin gram_in
#define yyleng gram_leng
#define yylex gram_lex
#define yyout gram_out
#define yyrestart gram_restart
#define yytext gram_text

#line 19 "scan-gram.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[355] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   93,   44,
       33,   32,   32,   37,   44,   36,   34,   44,   35,   29,
       31,   44,   28,   41,   30,   48,   49,   49,   50,   45,
       46,   73,   75,   75,   72,   45,   92,   46,   69,   71,
       71,   68,   92,   52,   53,   53,   51,   92,   55,   56,
       56,   54,   84,   85,   85,   77,   86,   76,   86,   86,
       45,   46,   81,   80,   88,   90,   90,   77,   92,   76,
       88,   91,   91,   91,   77,   76,   91,   33,   32,   32,
       32,   32,   43,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   40,   34,   38,
       39,   35,    0,   48,   49,   49,   49,   49,   47,   73,
       75,   75,   75,   75,   74,   71,   71,   71,   71,   70,
       52,   53,   53,   53,   53,   67,   66,   67,   59,   60,
       61,   62,   63,   64,   65,   67,   56,   56,   56,   56,
       84,   85,   85,   85,   85,   82,    0,   82,    0,   78,
       79,   83,    0,   83,   88,   90,   90,   90,   90,   89,
        0,   87,   78,   79,   91,   91,   91,   91,   91,   78,
       79,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   39,   42,    0,    0,    0,    0,   79,
       79,   79,   79,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   57,   58,
       82,    0,   82,    0,    0,    0,    0,    0,    0,    0,
        9,    0,    0,    0,    0,    0,    0,   16,    0,    0,
        0,    0,   21,    0,   24,    0,    0,   27,    0,    2,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   14,
        0,    0,   18,    0,   20,   22,   25,    0,    1,    3,
        0,    6,    0,    0,    0,    0,    0,    0,   15,    0,

        0,    0,    0,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   26,    0,    0,    0,    0,    0,
       12,   13,    0,   19,    0,    0,    0,    0,   10,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    7,
        0,   11,   17,   23,    0,    0,    5,    0,    0,    0,
        0,    0,    8,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    6,    7,    1,    8,    1,
        1,    9,    1,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   14,   14,   15,   16,   17,
       18,   19,    1,   20,   21,   21,   21,   21,   21,   21,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       22,   23,   24,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   11,   35,   36,   37,   38,
       39,   40,   11,   41,   42,   43,   44,   45,   11,   46,
       47,   11,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    2,    3,    4,    5,    6,    5,    7,    1,
        8,    5,    9,    9,    1,    1,    1,    1,   10,    5,
        9,   11,   12,   11,    8,    9,    9,    9,    9,    9,
        9,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    5,    1,    5
    } ;

static yyconst short int yy_base[382] =
    {   0,
        0,    0,   48,   51,   58,   61,   83,   86,   73,   94,
      108,  110,  131,  179,  227,  249,  116,  142,  798,  799,
      795,   55,   64,  799,  267,  799,    0,   44,   79,  799,
      799,    0,  799,  799,  799,    0,   97,   99,  784,  799,
      799,    0,  119,  122,  799,  799,    0,  799,  799,  126,
      138,  799,    0,    0,  145,  153,  799,  311,  799,  155,
      157,  799,    0,  159,  164,  799,  159,  799,   62,  164,
      799,  799,  799,  799,    0,  185,  189,    0,  125,    0,
      185,  192,  201,  203,  205,  207,  209,  793,  211,  213,
      216,  219,  799,  760,  763,  187,  758,   49,  198,  747,

      199,  756,  109,  208,  751,  758,  761,  799,    0,  799,
        0,  212,  767,    0,  241,  255,  259,  261,  799,    0,
      263,  265,  272,  274,  799,  276,  278,  280,  282,  799,
        0,  284,  286,  288,  296,  799,  799,  772,  799,  799,
      799,  799,  799,  799,  799,    0,  298,  314,  316,  318,
        0,  322,  324,  326,  328,  799,  322,  326,  765,  799,
        0,  799,  330,  332,    0,  344,  347,  355,  357,  243,
      263,  799,    0,  358,  360,  363,  365,  367,  369,  371,
      373,  745,  159,  741,  741,  200,  749,  751,  741,  368,
      747,  733,  745,  733,  741,  742,  745,  729,  734,  728,

      733,  725,  737,    0,  799,  751,    0,  744,  373,    0,
      377,  385,  399,  736,  717,  726,  720,  728,  727,  726,
      712,  728,  723,  716,  725,  709,  709,  720,  717,  713,
      709,  703,  706,  712,  711,  701,  712,  710,  799,  799,
      718,  377,  391,  695,  703,  696,  692,  704,  721,  701,
      799,  686,  375,  694,  685,  689,  681,  799,  388,  681,
      693,  679,  799,  683,  799,  682,  680,  799,  671,  799,
      665,  401,  640,  631,  402,  625,  616,  598,  593,  799,
      589,  587,  799,  581,  799,  404,  799,  581,  799,  578,
      569,  799,  572,  573,  572,  558,  560,  550,  799,  562,

      537,  521,  526,  799,  525,  524,  507,  509,  513,  500,
      510,  387,  387,  398,  799,  381,  389,  376,  376,  386,
      799,  799,  374,  799,  381,  367,  321,  313,  799,  307,
      303,  287,  265,  249,  228,  214,  207,  212,  160,  799,
      157,  799,  799,  799,  168,  405,  799,  149,  137,   91,
       85,   62,  799,  799,  430,  442,  454,  466,  478,  490,
      502,  514,  519,  528,  540,  552,  562,  574,  586,  597,
      609,  621,  633,  645,  657,   86,  669,  681,  693,  705,
       60
    } ;

static yyconst short int yy_def[382] =
    {   0,
      354,    1,  355,  355,  356,  356,  357,  357,  358,  358,
      359,  359,  360,  360,  361,  361,  362,  362,  354,  354,
      354,  354,  354,  354,  354,  354,  363,  354,  354,  354,
      354,  364,  354,  354,  354,  365,  354,  354,  354,  354,
      354,  366,  354,  354,  354,  354,  367,  354,  354,  354,
      354,  354,  368,  369,  354,  354,  354,  370,  354,  354,
      354,  354,  371,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  372,  354,  354,  372,  373,  372,
      372,  374,  374,  374,  374,  374,  374,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  363,  354,
      375,  354,  364,  365,  354,  354,  354,  354,  354,  366,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      369,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  376,  354,  354,  354,  354,
      371,  354,  354,  354,  354,  354,  354,  354,  377,  354,
      378,  354,  354,  354,  372,  354,  354,  354,  354,  373,
      373,  354,  372,  379,  374,  374,  374,  374,  374,  374,
      380,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  375,  354,  354,  381,  377,  377,  378,
      379,  380,  380,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      377,  377,  377,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,    0,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354
    } ;

static yyconst short int yy_nxt[850] =
    {   0,
       20,   21,   22,   23,   24,   20,   25,   26,   20,   20,
       27,   28,   29,   29,   30,   31,   32,   33,   20,   20,
       27,   20,   20,   20,   20,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   34,   35,   20,
       37,   38,  110,   37,   38,  111,   39,   89,   90,   39,
       43,   44,   45,   43,   44,   45,   91,   92,  240,   40,
      160,   41,   40,  161,   41,   55,   56,   57,  187,   46,
       47,   48,   46,   47,   48,   50,   51,  188,   50,   51,
       52,  112,  112,   52,  207,   58,   55,   56,   57,  115,

      116,  117,  118,  353,   46,   53,   48,   46,   53,   48,
       60,   61,   60,   61,  352,   62,   58,   62,   83,   84,
       85,  121,  122,   86,  123,  124,  351,   87,  126,  127,
       58,  171,   58,   64,   65,   66,   67,   46,   68,   48,
      128,  129,   69,  196,   83,   84,   85,  132,  133,   86,
       70,  197,   71,   87,   72,  134,  135,  147,  148,  149,
      150,  152,  153,   46,  156,   48,  154,  155,  157,  162,
      350,  158,  158,  163,  172,  159,  164,  164,   73,  349,
       74,   64,   65,   66,   67,  215,   68,  166,  167,  216,
       69,  168,  169,  173,  176,  177,  174,  347,   70,  346,

       71,  345,   72,  176,  178,  179,  177,  176,  177,  176,
      177,  176,  177,   89,   90,   91,   92,  180,   89,   90,
      181,   91,   92,  189,  112,  112,   73,  184,   74,   76,
       77,   78,  185,   79,   80,  219,  190,  198,   81,  193,
      191,  344,  194,  115,  116,  220,  199,  343,   46,  354,
       48,   76,   77,   78,  200,   79,   80,  117,  118,  342,
       81,  115,  116,  117,  118,  121,  122,  123,  124,  171,
       46,  341,   48,   93,  121,  122,  123,  124,  126,  127,
      128,  129,  126,  127,  128,  129,  132,  133,  134,  135,
      132,  133,  354,   94,  340,   95,   96,   97,  134,  135,

      147,  148,   98,  339,   99,  100,  101,  102,  103,  104,
      105,  106,  354,  107,  108,  137,  149,  150,  147,  148,
      149,  150,  338,  138,  152,  153,  154,  155,  152,  153,
      154,  155,  337,  137,  158,  158,  139,  140,  158,  158,
      336,  141,  164,  164,  164,  164,  166,  167,  142,  168,
      169,  143,  335,  144,  334,  145,  146,  166,  167,  168,
      169,  210,  176,  177,  210,  176,  178,  179,  177,  179,
      177,  176,  178,  176,  177,  176,  213,  224,  241,  210,
      210,  210,  242,  210,  277,  243,  243,  176,  213,  243,
      243,  209,  224,  333,  210,  209,  210,  282,  210,  277,

      210,  179,  213,  243,  243,  225,  210,  332,  210,  209,
      291,  294,  282,  302,  348,  331,  330,  329,  328,  327,
      210,  326,  210,  325,  324,  291,  294,  323,  302,  348,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,  109,  109,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  322,  113,  113,
      114,  321,  320,  114,  114,  114,  319,  114,  114,  114,
      318,  114,  120,  317,  316,  315,  120,  120,  120,  120,
      120,  120,  125,  314,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  130,  313,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  131,  312,  311,  310,
      131,  131,  131,  131,  131,  131,  131,  136,  309,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  151,
      308,  307,  306,  305,  151,  151,  151,  151,  151,  304,
      151,  165,  303,  301,  165,  165,  300,  165,  165,  165,
      165,  299,  165,  170,  298,  297,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  296,  175,  204,  295,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  208,
      293,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  210,  292,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  211,  290,  211,  211,  211,  211,  211,

      211,  211,  211,  211,  211,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  289,  288,  287,
      286,  285,  284,  283,  281,  280,  279,  278,  276,  275,
      274,  273,  272,  271,  270,  269,  209,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  209,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  223,  222,  221,
      218,  217,  214,  209,  206,  205,  203,  202,  201,  195,
      192,  186,  183,  182,   88,  119,   88,  354,   19,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354
    } ;

static yyconst short int yy_chk[850] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,   28,    4,    4,   28,    3,   22,   22,    4,
        5,    5,    5,    6,    6,    6,   23,   23,  381,    3,
       69,    3,    4,   69,    4,    9,    9,    9,   98,    5,
        5,    5,    6,    6,    6,    7,    7,   98,    8,    8,
        7,   29,   29,    8,  376,    9,   10,   10,   10,   37,

       37,   38,   38,  352,    7,    7,    7,    8,    8,    8,
       11,   11,   12,   12,  351,   11,   10,   12,   17,   17,
       17,   43,   43,   17,   44,   44,  350,   17,   50,   50,
       11,   79,   12,   13,   13,   13,   13,   17,   13,   17,
       51,   51,   13,  103,   18,   18,   18,   55,   55,   18,
       13,  103,   13,   18,   13,   56,   56,   60,   60,   61,
       61,   64,   64,   18,   67,   18,   65,   65,   67,   70,
      349,   67,   67,   70,   79,   67,   70,   70,   13,  348,
       13,   14,   14,   14,   14,  183,   14,   76,   76,  183,
       14,   77,   77,   81,   82,   82,   81,  345,   14,  341,

       14,  339,   14,   83,   83,   84,   84,   85,   85,   86,
       86,   87,   87,   89,   89,   90,   90,   87,   91,   91,
       87,   92,   92,   99,  112,  112,   14,   96,   14,   15,
       15,   15,   96,   15,   15,  186,   99,  104,   15,  101,
       99,  338,  101,  115,  115,  186,  104,  337,   15,  170,
       15,   16,   16,   16,  104,   16,   16,  116,  116,  336,
       16,  117,  117,  118,  118,  121,  121,  122,  122,  171,
       16,  335,   16,   25,  123,  123,  124,  124,  126,  126,
      127,  127,  128,  128,  129,  129,  132,  132,  133,  133,
      134,  134,  170,   25,  334,   25,   25,   25,  135,  135,

      147,  147,   25,  333,   25,   25,   25,   25,   25,   25,
       25,   25,  171,   25,   25,   58,  148,  148,  149,  149,
      150,  150,  332,   58,  152,  152,  153,  153,  154,  154,
      155,  155,  331,   58,  157,  157,   58,   58,  158,  158,
      330,   58,  163,  163,  164,  164,  166,  166,   58,  167,
      167,   58,  328,   58,  327,   58,   58,  168,  168,  169,
      169,  174,  175,  175,  174,  176,  176,  177,  177,  178,
      178,  179,  179,  180,  180,  181,  181,  190,  209,  174,
      211,  174,  209,  211,  253,  209,  209,  212,  212,  242,
      242,  209,  190,  326,  181,  242,  181,  259,  211,  253,

      211,  213,  213,  243,  243,  190,  212,  325,  212,  243,
      272,  275,  259,  286,  346,  323,  320,  319,  318,  317,
      213,  316,  213,  314,  313,  272,  275,  312,  286,  346,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  363,  363,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  311,  364,  364,
      365,  310,  309,  365,  365,  365,  308,  365,  365,  365,
      307,  365,  366,  306,  305,  303,  366,  366,  366,  366,
      366,  366,  367,  302,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  368,  301,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  369,  300,  298,  297,
      369,  369,  369,  369,  369,  369,  369,  370,  296,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  371,
      295,  294,  293,  291,  371,  371,  371,  371,  371,  290,
      371,  372,  288,  284,  372,  372,  282,  372,  372,  372,
      372,  281,  372,  373,  279,  278,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  277,  374,  375,  276,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  377,
      274,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  378,  273,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  379,  271,  379,  379,  379,  379,  379,

      379,  379,  379,  379,  379,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  269,  267,  266,
      264,  262,  261,  260,  257,  256,  255,  254,  252,  250,
      249,  248,  247,  246,  245,  244,  241,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  208,  206,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  189,  188,  187,
      185,  184,  182,  159,  138,  113,  107,  106,  105,  102,
      100,   97,   95,   94,   88,   39,   21,   19,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[92] =
    {   0,
      115,  116,  117,  118,  119,  120,  121,  122,  123,  124,
      125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
      135,  136,  137,  138,  139,  140,  141,  143,  144,  145,
      146,  148,  149,  150,  157,  160,  163,  166,  167,  170,
      173,  176,  178,  184,  200,  201,  212,  224,  225,  226,
      243,  251,  253,  272,  286,  288,  307,  319,  323,  324,
      325,  326,  327,  328,  329,  330,  331,  346,  352,  353,
      355,  373,  379,  380,  382,  400,  403,  406,  407,  418,
      428,  430,  431,  433,  434,  437,  456,  462,  463,  464,
      484

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan-gram.l"
#define INITIAL 0
/* Bison Grammar Scanner                             -*- C -*-
   Copyright (C) 2002 Free Software Foundation, Inc.

   This file is part of Bison, the GNU Compiler Compiler.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
   02111-1307  USA
*/
#define YY_NO_UNPUT 1
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#line 26 "scan-gram.l"
#include "system.h"
#include "complain.h"
#include "quote.h"
#include "getargs.h"
#include "gram.h"
#include "reader.h"

/* Each time we match a string, move the end cursor to its end. */
#define YY_USER_ACTION  LOCATION_COLUMNS (*yylloc, yyleng)
#define YY_LINES        LOCATION_LINES (*yylloc, yyleng); lineno += yyleng;
#define YY_STEP         LOCATION_STEP (*yylloc)


/* STRING_OBSTACK -- Used to store all the characters that we need to
   keep (to construct ID, STRINGS etc.).  Use the following macros to
   use it.

   Use YY_OBS_INIT to initialize a new growing string, YY_OBS_GROW to
   append what has just been matched, and YY_OBS_FINISH to end the
   string (it puts the ending 0).  YY_OBS_FINISH also stores this
   string in LAST_STRING, which can be used, and which is used by
   YY_OBS_FREE to free the last string.  */

static struct obstack string_obstack;
char *last_string;

#define YY_OBS_INIT   \
  obstack_init (&string_obstack)

#define YY_OBS_GROW   \
  obstack_grow (&string_obstack, yytext, yyleng)

#define YY_OBS_FINISH					\
  do {							\
    obstack_1grow (&string_obstack, '\0');		\
    last_string = obstack_finish (&string_obstack);	\
    yylval->string = last_string;			\
  } while (0)

#define YY_OBS_FREE						\
  do {								\
    obstack_free (&string_obstack, last_string);		\
  } while (0)

/* This is only to avoid GCC warnings. */
#define YY_USER_INIT    if (yycontrol) {;};


static int braces_level = 0;
static int percent_percent_count = 0;

static void handle_dollar PARAMS ((char *cp));
static void handle_at PARAMS ((char *cp));

#define SC_COMMENT 1

#define SC_STRING 2
#define SC_CHARACTER 3

#define SC_ESCAPED_STRING 4
#define SC_ESCAPED_CHARACTER 5

#define SC_BRACED_CODE 6
#define SC_PROLOGUE 7
#define SC_EPILOGUE 8

#line 806 "scan-gram.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 91 "scan-gram.l"


  /* At each yylex invocation, mark the current position as the
     start of the next token.  */
#define TR_POS 0
#if TR_POS
  fprintf (stderr, "FOO1: ");
  LOCATION_PRINT (stderr, *yylloc);
  fprintf (stderr, "\n");
#endif
  YY_STEP;
#if TR_POS
  fprintf (stderr, "BAR1: ");
  LOCATION_PRINT (stderr, *yylloc);
  fprintf (stderr, "\n");
#endif



  /*----------------------------.
  | Scanning Bison directives.  |
  `----------------------------*/
#line 991 "scan-gram.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 355 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 799 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 92 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 92 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 93 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;



case 1:
YY_RULE_SETUP
#line 115 "scan-gram.l"
return PERCENT_NONASSOC;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 116 "scan-gram.l"
return PERCENT_DEBUG;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 117 "scan-gram.l"
return PERCENT_DEFINE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "scan-gram.l"
return PERCENT_DEFINES;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 "scan-gram.l"
return PERCENT_ERROR_VERBOSE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 120 "scan-gram.l"
return PERCENT_EXPECT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 121 "scan-gram.l"
return PERCENT_FILE_PREFIX;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 122 "scan-gram.l"
return PERCENT_YACC;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "scan-gram.l"
return PERCENT_LEFT;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 124 "scan-gram.l"
return PERCENT_LOCATIONS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 125 "scan-gram.l"
return PERCENT_NAME_PREFIX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 126 "scan-gram.l"
return PERCENT_NO_LINES;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 127 "scan-gram.l"
return PERCENT_NONASSOC;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 128 "scan-gram.l"
return PERCENT_NTERM;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 129 "scan-gram.l"
return PERCENT_OUTPUT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "scan-gram.l"
return PERCENT_PREC;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 131 "scan-gram.l"
return PERCENT_PURE_PARSER;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 132 "scan-gram.l"
return PERCENT_RIGHT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 133 "scan-gram.l"
return PERCENT_SKELETON;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 134 "scan-gram.l"
return PERCENT_START;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 135 "scan-gram.l"
return PERCENT_TOKEN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 136 "scan-gram.l"
return PERCENT_TOKEN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 137 "scan-gram.l"
return PERCENT_TOKEN_TABLE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 138 "scan-gram.l"
return PERCENT_TYPE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 139 "scan-gram.l"
return PERCENT_UNION;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 140 "scan-gram.l"
return PERCENT_VERBOSE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 141 "scan-gram.l"
return PERCENT_YACC;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 143 "scan-gram.l"
return EQUAL;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 144 "scan-gram.l"
return COLON;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 145 "scan-gram.l"
return PIPE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 146 "scan-gram.l"
return SEMICOLON;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 148 "scan-gram.l"
YY_LINES; YY_STEP;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 149 "scan-gram.l"
YY_STEP;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 150 "scan-gram.l"
{
    YY_OBS_INIT; YY_OBS_GROW; YY_OBS_FINISH;
    yylval->symbol = getsym (last_string);
    YY_OBS_FREE;
    return ID;
  }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 157 "scan-gram.l"
yylval->integer = strtol (yytext, 0, 10); return INT;
	YY_BREAK
/* Characters.  We don't check there is only one.  */
case 36:
YY_RULE_SETUP
#line 160 "scan-gram.l"
YY_OBS_INIT; YY_OBS_GROW; yy_push_state (SC_ESCAPED_CHARACTER);
	YY_BREAK
/* Strings. */
case 37:
YY_RULE_SETUP
#line 163 "scan-gram.l"
YY_OBS_INIT; YY_OBS_GROW; yy_push_state (SC_ESCAPED_STRING);
	YY_BREAK
/* Comments. */
case 38:
YY_RULE_SETUP
#line 166 "scan-gram.l"
yy_push_state (SC_COMMENT);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "scan-gram.l"
YY_STEP;
	YY_BREAK
/* Prologue. */
case 40:
YY_RULE_SETUP
#line 170 "scan-gram.l"
YY_OBS_INIT; yy_push_state (SC_PROLOGUE);
	YY_BREAK
/* Code in between braces.  */
case 41:
YY_RULE_SETUP
#line 173 "scan-gram.l"
YY_OBS_INIT; YY_OBS_GROW; ++braces_level; yy_push_state (SC_BRACED_CODE);
	YY_BREAK
/* A type. */
case 42:
YY_RULE_SETUP
#line 176 "scan-gram.l"
YY_OBS_INIT; obstack_grow (&string_obstack, yytext + 1, yyleng - 2); YY_OBS_FINISH; return TYPE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 178 "scan-gram.l"
{
    if (++percent_percent_count == 2)
      yy_push_state (SC_EPILOGUE);
    return PERCENT_PERCENT;
  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 184 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": invalid character: `%c'\n", *yytext);
    YY_STEP;
  }
	YY_BREAK

/*------------------------------------------------------------.
  | Whatever the start condition (but those which correspond to |
  | entity `swallowed' by Bison: SC_ESCAPED_STRING and          |
  | SC_ESCAPED_CHARACTER), no M4 character must escape as is.   |
  `------------------------------------------------------------*/


case 45:
YY_RULE_SETUP
#line 200 "scan-gram.l"
obstack_sgrow (&string_obstack, "@<:@");
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 201 "scan-gram.l"
obstack_sgrow (&string_obstack, "@:>@");
	YY_BREAK

/*-----------------------------------------------------------.
  | Scanning a C comment. The initial `/ *' is already eaten.  |
  `-----------------------------------------------------------*/


case 47:
YY_RULE_SETUP
#line 212 "scan-gram.l"
{ /* End of the comment. */
    if (yy_top_state () == INITIAL)
      {
	YY_STEP;
      }
    else
      {
	YY_OBS_GROW;
      }
    yy_pop_state ();
  }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 224 "scan-gram.l"
if (yy_top_state () != INITIAL) YY_OBS_GROW;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 225 "scan-gram.l"
if (yy_top_state () != INITIAL) YY_OBS_GROW; YY_LINES;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 226 "scan-gram.l"
/* Stray `*'. */if (yy_top_state () != INITIAL) YY_OBS_GROW;
	YY_BREAK
case YY_STATE_EOF(SC_COMMENT):
#line 228 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a comment\n");
    yy_pop_state ();
  }
	YY_BREAK

/*----------------------------------------------------------------.
  | Scanning a C string, including its escapes.  The initial `"' is |
  | already eaten.                                                  |
  `----------------------------------------------------------------*/


case 51:
YY_RULE_SETUP
#line 243 "scan-gram.l"
{
    assert (yy_top_state () == INITIAL);
    YY_OBS_GROW;
    YY_OBS_FINISH;
    yy_pop_state ();
    return STRING;
  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 251 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 253 "scan-gram.l"
obstack_1grow (&string_obstack, '\n'); YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_ESCAPED_STRING):
#line 255 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a string\n");
    assert (yy_top_state () == INITIAL);
    YY_OBS_FINISH;
    yy_pop_state ();
    return STRING;
  }
	YY_BREAK

/*---------------------------------------------------------------.
  | Scanning a C character, decoding its escapes.  The initial "'" |
  | is already eaten.                                              |
  `---------------------------------------------------------------*/


case 54:
YY_RULE_SETUP
#line 272 "scan-gram.l"
{
    YY_OBS_GROW;
    assert (yy_top_state () == INITIAL);
    {
      YY_OBS_FINISH;
      yylval->symbol = getsym (last_string);
      symbol_class_set (yylval->symbol, token_sym);
      symbol_user_token_number_set (yylval->symbol, last_string[1]);
      YY_OBS_FREE;
      yy_pop_state ();
      return ID;
    }
  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 286 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 288 "scan-gram.l"
obstack_1grow (&string_obstack, '\n'); YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_ESCAPED_CHARACTER):
#line 290 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a character\n");
    assert (yy_top_state () == INITIAL);
    YY_OBS_FINISH;
    yy_pop_state ();
    return CHARACTER;
  }
	YY_BREAK

/*----------------------------.
  | Decode escaped characters.  |
  `----------------------------*/


case 57:
YY_RULE_SETUP
#line 307 "scan-gram.l"
{
    long c = strtol (yytext + 1, 0, 8);
    if (c > 255)
      {
	LOCATION_PRINT (stderr, *yylloc);
	fprintf (stderr, ": invalid escape: %s\n", yytext);
	YY_STEP;
      }
    else
      obstack_1grow (&string_obstack, c);
  }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 319 "scan-gram.l"
{
    obstack_1grow (&string_obstack, strtol (yytext + 2, 0, 16));
  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 323 "scan-gram.l"
obstack_1grow (&string_obstack, '\a');
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 324 "scan-gram.l"
obstack_1grow (&string_obstack, '\b');
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 325 "scan-gram.l"
obstack_1grow (&string_obstack, '\f');
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 326 "scan-gram.l"
obstack_1grow (&string_obstack, '\n');
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 327 "scan-gram.l"
obstack_1grow (&string_obstack, '\r');
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 328 "scan-gram.l"
obstack_1grow (&string_obstack, '\t');
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 329 "scan-gram.l"
obstack_1grow (&string_obstack, '\v');
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 330 "scan-gram.l"
obstack_1grow (&string_obstack, yytext[1]);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 331 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unrecognized escape: %s\n", yytext);
    YY_OBS_GROW;
  }
	YY_BREAK

/*----------------------------------------------------------.
  | Scanning a C character without decoding its escapes.  The |
  | initial "'" is already eaten.                             |
  `----------------------------------------------------------*/


case 68:
YY_RULE_SETUP
#line 346 "scan-gram.l"
{
    YY_OBS_GROW;
    assert (yy_top_state () != INITIAL);
    yy_pop_state ();
  }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 352 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 353 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 355 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_CHARACTER):
#line 357 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a character\n");
    assert (yy_top_state () != INITIAL);
    yy_pop_state ();
  }
	YY_BREAK

/*----------------------------------------------------------------.
  | Scanning a C string, without decoding its escapes.  The initial |
  | `"' is already eaten.                                           |
  `----------------------------------------------------------------*/


case 72:
YY_RULE_SETUP
#line 373 "scan-gram.l"
{
    assert (yy_top_state () != INITIAL);
    YY_OBS_GROW;
    yy_pop_state ();
  }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 379 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 380 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 382 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_STRING):
#line 384 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a string\n");
    assert (yy_top_state () != INITIAL);
    yy_pop_state ();
  }
	YY_BREAK

/*---------------------------------------------------.
  | Strings, comments etc. can be found in user code.  |
  `---------------------------------------------------*/


/* Characters.  We don't check there is only one.  */
case 76:
YY_RULE_SETUP
#line 400 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_CHARACTER);
	YY_BREAK
/* Strings. */
case 77:
YY_RULE_SETUP
#line 403 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_STRING);
	YY_BREAK
/* Comments. */
case 78:
YY_RULE_SETUP
#line 406 "scan-gram.l"
YY_OBS_GROW; yy_push_state (SC_COMMENT);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 407 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK

/*---------------------------------------------------------------.
  | Scanning some code in braces (%union and actions). The initial |
  | "{" is already eaten.                                          |
  `---------------------------------------------------------------*/


case 80:
YY_RULE_SETUP
#line 418 "scan-gram.l"
{
    YY_OBS_GROW;
    if (--braces_level == 0)
      {
	yy_pop_state ();
	YY_OBS_FINISH;
	return BRACED_CODE;
      }
  }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 428 "scan-gram.l"
YY_OBS_GROW; braces_level++;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 430 "scan-gram.l"
{ handle_dollar (yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 431 "scan-gram.l"
{ handle_at (yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 433 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 434 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
/* A lose $, or /, or etc. */
case 86:
YY_RULE_SETUP
#line 437 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case YY_STATE_EOF(SC_BRACED_CODE):
#line 439 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a braced code\n");
    yy_pop_state ();
    YY_OBS_FINISH;
    return PROLOGUE;
  }
	YY_BREAK

/*--------------------------------------------------------------.
  | Scanning some prologue: from "%{" (already scanned) to "%}".  |
  `--------------------------------------------------------------*/


case 87:
YY_RULE_SETUP
#line 456 "scan-gram.l"
{
    yy_pop_state ();
    YY_OBS_FINISH;
    return PROLOGUE;
  }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 462 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 463 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 464 "scan-gram.l"
YY_OBS_GROW; YY_LINES;
	YY_BREAK
case YY_STATE_EOF(SC_PROLOGUE):
#line 466 "scan-gram.l"
{
    LOCATION_PRINT (stderr, *yylloc);
    fprintf (stderr, ": unexpected end of file in a prologue\n");
    yy_pop_state ();
    YY_OBS_FINISH;
    return PROLOGUE;
  }
	YY_BREAK

/*---------------------------------------------------------------.
  | Scanning the epilogue (everything after the second "%%", which |
  | has already been eaten.                                        |
  `---------------------------------------------------------------*/


case 91:
YY_RULE_SETUP
#line 484 "scan-gram.l"
YY_OBS_GROW;
	YY_BREAK
case YY_STATE_EOF(SC_EPILOGUE):
#line 486 "scan-gram.l"
{
    yy_pop_state ();
    YY_OBS_FINISH;
    return EPILOGUE;
  }
	YY_BREAK

case 92:
YY_RULE_SETUP
#line 494 "scan-gram.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1789 "scan-gram.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 355 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 355 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 354);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 494 "scan-gram.l"


/*------------------------------------------------------------------.
| CP is pointing to a wannabee semantic value (i.e., a `$').        |
|                                                                   |
| Possible inputs: $[<TYPENAME>]($|integer)                         |
|                                                                   |
| Output to the STRING_OBSTACK a reference to this semantic value.  |
`------------------------------------------------------------------*/

static void
handle_dollar (char *cp)
{
  const char *type_name = NULL;

  /* RULE_LENGTH is the number of values in the current rule so far,
     which says where to find `$0' with respect to the top of the
     stack.  It is not the same as the rule->length in the case of mid
     rule actions.  */
  int rule_length = 0;
  symbol_list *rhs;
  for (rhs = current_rule->next; rhs; rhs = rhs->next)
    ++rule_length;

  ++cp;

  /* Get the type name if explicit. */
  if (*cp == '<')
    {
      type_name = ++cp;
      while (*cp != '>')
	++cp;
      *cp = '\0';
      ++cp;
    }

  if (*cp == '$')
    {
      if (!type_name)
	type_name = get_type_name (0, current_rule);
      if (!type_name && typed)
	complain (_("$$ of `%s' has no declared type"),
		  current_rule->sym->tag);
      if (!type_name)
	type_name = "";
      obstack_fgrow1 (&string_obstack,
		      "]b4_lhs_value([%s])[", type_name);
    }
  else if (isdigit (*cp) || *cp == '-')
    {
      int n = strtol (cp, &cp, 10);

      if (n > rule_length)
	complain (_("invalid value: %s%d"), "$", n);
      else
	{
	  if (!type_name && n > 0)
	    type_name = get_type_name (n, current_rule);
	  if (!type_name && typed)
	    complain (_("$%d of `%s' has no declared type"),
		      n, current_rule->sym->tag);
	  if (!type_name)
	    type_name = "";
	  obstack_fgrow3 (&string_obstack,
			  "]b4_rhs_value([%d], [%d], [%s])[",
			  rule_length, n, type_name);
	}
    }
  else
    {
      char buf[] = "$c";
      buf[1] = *cp;
      complain (_("%s is invalid"), quote (buf));
    }
}

/*-------------------------------------------------------.
| CP is pointing to a location (i.e., a `@').  Output to |
| STRING_OBSTACK a reference to this location.           |
`-------------------------------------------------------*/

static void
handle_at (char *cp)
{
  /* RULE_LENGTH is the number of values in the current rule so far,
     which says where to find `$0' with respect to the top of the
     stack.  It is not the same as the rule->length in the case of mid
     rule actions.  */
  int rule_length = 0;
  symbol_list *rhs;
  for (rhs = current_rule->next; rhs; rhs = rhs->next)
    ++rule_length;

  locations_flag = 1;
  ++cp;

  if (*cp == '$')
    {
      obstack_sgrow (&string_obstack, "]b4_lhs_location[");
    }
  else if (isdigit (*cp) || *cp == '-')
    {
      int n = strtol (cp, &cp, 10);
      if (n > rule_length)
	complain (_("invalid value: %s%d"), "@", n);
      else
	obstack_fgrow2 (&string_obstack, "]b4_rhs_location([%d], [%d])[",
			rule_length, n);
    }
  else
    {
      char buf[] = "@c";
      buf[1] = *cp;
      complain (_("%s is invalid"), quote (buf));
    }
}
